/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasteori12;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author asus
 */
public class frmSelectBarang extends javax.swing.JFrame {
    Connection Con; 
    ResultSet RsBrg; 
    Statement stm; 
    public frmTransaksi fAB = null; 
    private Object[][] dataTable = null; 
    private String[] header = {"Kode","Nama Barang","Satuan","Harga","Harga Beli","Stok","Stok Min"}; }
         
    /**
     * Creates new form frmBarang
     */
    public frmSelectBarang() {
        initComponents();
        baca_data();
    }

    private void open_db() 
    { 
        try{ 
       KoneksiMysql kon = new KoneksiMysql 
        ("127.0.0.1","root","","penjualan"); 
       Con = kon.getConnection(); 
       } 
        catch (Exception e) { 
        System.out.println("Error : "+e); 
       }
    } 
    private void baca_data() 
        {open_db(); 
         try{ 
         stm = Con.createStatement(); 
         RsBrg = stm.executeQuery("select * from barang order by kd_brg"); 

         ResultSetMetaData meta = RsBrg.getMetaData(); 
         int col = meta.getColumnCount(); 
         int baris = 0; 
         while(RsBrg.next()) { 
         baris = RsBrg.getRow(); 
         } 

         dataTable = new Object[baris][col]; 
         int x = 0; 
         RsBrg.beforeFirst(); 
         while(RsBrg.next()) { 
         dataTable[x][0] = RsBrg.getString("kd_brg"); 
         dataTable[x][1] = RsBrg.getString("nm_brg"); 
         dataTable[x][2] = RsBrg.getString("satuan"); 
         dataTable[x][3] = RsBrg.getDouble("harga"); 
         dataTable[x][4] = RsBrg.getDouble("harga_beli"); 
         dataTable[x][5] = RsBrg.getInt("stok"); 
         dataTable[x][6] = RsBrg.getInt("stok_min"); 
         x++; 
         } 
         tblBrg.setModel(new DefaultTableModel(dataTable,header)); 
         } 
         catch(SQLException e) 
         { 
         JOptionPane.showMessageDialog(null, e); 
         } 
        } 
         private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) { 
         int row=tblBrg.getSelectedRow(); 
         int tabelBarang = tblBrg.getSelectedRow(); 
        fAB.idBrg = tblBrg.getValueAt(tabelBarang, 0).toString(); 
        fAB.namaBrg = tblBrg.getValueAt(tabelBarang, 1).toString(); 
        fAB.hargaBrg = tblBrg.getValueAt(tabelBarang, 3).toString(); 
        fAB.itemTerpilih(); 
        this.dispose(); 
     } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tblBarang = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Barang");

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Satuan", "Harga", "Harga Beli", "Stok", "Stok Minimal"
            }
        ));
        tblBarang.setViewportView(tblBrg);

        jLabel2.setText("*Click pada baris untuk produk yang dipilih");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tblBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane tblBarang;
    private javax.swing.JTable tblBrg;
    // End of variables declaration//GEN-END:variables
}
